version: '{build}'

image: Visual Studio 2022

environment:
  VERSION: 1.2.0
  TARGET_CONFIGURATION: Release

platform: Any CPU

branches:
  only:
    - master

only_commits:
  message: /build/
#  files:
#    - src/*

before_build:
- cmd: >-
    dotnet --version

    dotnet restore

build_script:
- cmd: >-
    dotnet pack .\src\Doulex.DistributedCache -c %TARGET_CONFIGURATION% -p:VersionPrefix=%VERSION% 

artifacts:
  - path: "src/**/*.nupkg"
    name: "Doulex.DistributedCache NuGet Packages"

deploy:
  - provider: NuGet
    api_key:
      secure: UIRvzyHvZdb41Gixu5+IJ9nrOhfuj7Ey9mU52bL/kJAUFBLZN+tPQR2eydBnEDAp
    artifact: /.*\.nupkg/
